/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Ventanas;

import Controladores.ControladorProducto;
import Servicios.CarritoServicio;
import Servicios.ProductoServicio;
import javax.swing.JMenu;
import javax.swing.JMenuItem;


/**
 *
 * @author User
 */
public class VPrincipalView extends javax.swing.JFrame {
    /**
     * Creates new form PrincipalView
     */
    public VPrincipalView() {
        initComponents();
    }

    public JMenuItem getOpcionBuscarProducto() {
        return opcionBuscarProducto;
    }

    public JMenuItem getOpcionCrearProducto() {
        return opcionCrearCarritoOpcion;
    }

    public JMenuItem getOpcionEliminarProducto() {
        return OpcionEliminarProducto;
    }

    public JMenuItem getOpcionModificarProducto() {
        return opcionModificarProducto;
    }

    public JMenuItem getOpcionListarProductos() {
        return opcionListarProductos;
    }
    
    
    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        opcionCrearProducto = new javax.swing.JMenu();
        opcionCrearCarritoOpcion = new javax.swing.JMenuItem();
        opcionBuscarProducto = new javax.swing.JMenuItem();
        opcionModificarProducto = new javax.swing.JMenuItem();
        OpcionEliminarProducto = new javax.swing.JMenuItem();
        opcionListarProductos = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        opcionNuevoCarrito = new javax.swing.JMenuItem();
        OopcionBuscarCarrito = new javax.swing.JMenuItem();
        opcionModificarInformacionCarrito = new javax.swing.JMenuItem();
        opcionEliminarCarrito = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("---- SISTEMA DE COMPRAS ----");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 50);

        jPanel2.setBackground(new java.awt.Color(159, 162, 186));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("EL SISTEMA YA TIENE UNA BASE INICIAL, NO HACE FALTA AGREGAR ELEMETNOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("PARA PROBAR TODAS LAS FUNCIONALIDADES");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("LAS VENTANAS DE CARRITO NO TIENEN FUNCIONALIDAD, SOLO PRODUCTOS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel2);
        jPanel2.setBounds(0, 50, 880, 370);

        opcionCrearProducto.setMnemonic('f');
        opcionCrearProducto.setText("Producto");

        opcionCrearCarritoOpcion.setMnemonic('o');
        opcionCrearCarritoOpcion.setText("Crear Producto");
        opcionCrearCarritoOpcion.addActionListener(this::opcionCrearCarritoOpcionActionPerformed);
        opcionCrearProducto.add(opcionCrearCarritoOpcion);

        opcionBuscarProducto.setMnemonic('s');
        opcionBuscarProducto.setText("Buscar Producto");
        opcionBuscarProducto.addActionListener(this::opcionBuscarProductoActionPerformed);
        opcionCrearProducto.add(opcionBuscarProducto);

        opcionModificarProducto.setMnemonic('a');
        opcionModificarProducto.setText("Modificar Producto");
        opcionModificarProducto.addActionListener(this::opcionModificarProductoActionPerformed);
        opcionCrearProducto.add(opcionModificarProducto);

        OpcionEliminarProducto.setMnemonic('x');
        OpcionEliminarProducto.setText("Eliminar Producto");
        OpcionEliminarProducto.addActionListener(this::OpcionEliminarProductoActionPerformed);
        opcionCrearProducto.add(OpcionEliminarProducto);

        opcionListarProductos.setText("Listar Productos");
        opcionListarProductos.addActionListener(this::opcionListarProductosActionPerformed);
        opcionCrearProducto.add(opcionListarProductos);

        menuBar.add(opcionCrearProducto);

        editMenu.setMnemonic('e');
        editMenu.setText("Carrito");

        opcionNuevoCarrito.setMnemonic('t');
        opcionNuevoCarrito.setText("Nuevo Carrito");
        opcionNuevoCarrito.addActionListener(this::opcionNuevoCarritoActionPerformed);
        editMenu.add(opcionNuevoCarrito);

        OopcionBuscarCarrito.setMnemonic('y');
        OopcionBuscarCarrito.setText("Buscar Carrito");
        OopcionBuscarCarrito.addActionListener(this::OopcionBuscarCarritoActionPerformed);
        editMenu.add(OopcionBuscarCarrito);

        opcionModificarInformacionCarrito.setMnemonic('p');
        opcionModificarInformacionCarrito.setText("Modificar Informacion");
        opcionModificarInformacionCarrito.addActionListener(this::opcionModificarInformacionCarritoActionPerformed);
        editMenu.add(opcionModificarInformacionCarrito);

        opcionEliminarCarrito.setMnemonic('d');
        opcionEliminarCarrito.setText("Eliminar Carrito");
        opcionEliminarCarrito.addActionListener(this::opcionEliminarCarritoActionPerformed);
        editMenu.add(opcionEliminarCarrito);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Acerda de nosotros");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Contacto");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpcionEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionEliminarProductoActionPerformed

    }//GEN-LAST:event_OpcionEliminarProductoActionPerformed

    private void opcionCrearCarritoOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCrearCarritoOpcionActionPerformed

    }//GEN-LAST:event_opcionCrearCarritoOpcionActionPerformed

    private void opcionBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBuscarProductoActionPerformed

    }//GEN-LAST:event_opcionBuscarProductoActionPerformed

    private void opcionModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionModificarProductoActionPerformed

    }//GEN-LAST:event_opcionModificarProductoActionPerformed

    private void opcionListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionListarProductosActionPerformed

    }//GEN-LAST:event_opcionListarProductosActionPerformed

    private void opcionNuevoCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionNuevoCarritoActionPerformed

    }//GEN-LAST:event_opcionNuevoCarritoActionPerformed

    private void OopcionBuscarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OopcionBuscarCarritoActionPerformed

    }//GEN-LAST:event_OopcionBuscarCarritoActionPerformed

    private void opcionModificarInformacionCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionModificarInformacionCarritoActionPerformed

    }//GEN-LAST:event_opcionModificarInformacionCarritoActionPerformed

    private void opcionEliminarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEliminarCarritoActionPerformed

    }//GEN-LAST:event_opcionEliminarCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OopcionBuscarCarrito;
    private javax.swing.JMenuItem OpcionEliminarProducto;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem opcionBuscarProducto;
    private javax.swing.JMenuItem opcionCrearCarritoOpcion;
    private javax.swing.JMenu opcionCrearProducto;
    private javax.swing.JMenuItem opcionEliminarCarrito;
    private javax.swing.JMenuItem opcionListarProductos;
    private javax.swing.JMenuItem opcionModificarInformacionCarrito;
    private javax.swing.JMenuItem opcionModificarProducto;
    private javax.swing.JMenuItem opcionNuevoCarrito;
    // End of variables declaration//GEN-END:variables

}
