/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Ventanas;

import Controladores.ProductoControlador;
import Ventanas.VentanasCarrito.VBuscarCarritoView;
import Ventanas.VentanasCarrito.VEliminarCarritoView;
import Ventanas.VentanasCarrito.VModificarCarritoView;
import Ventanas.VentanasCarrito.VNuevoCarritoView;
import Ventanas.VentanasProducto.VAgregarProductoView;
import Ventanas.VentanasProducto.VBuscarProductoView;
import Ventanas.VentanasProducto.VEliminarProductoView;
import Ventanas.VentanasProducto.VListarProductosView;
import Ventanas.VentanasProducto.VModificarProductoView;


/**
 *
 * @author User
 */
public class VPrincipalView extends javax.swing.JFrame {

    private ProductoControlador controlador;
    /**
     * Creates new form PrincipalView
     */
    public VPrincipalView(ProductoControlador controlador) {
        this.controlador = controlador;
        initComponents();
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        opcionCrearProducto = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        opcionBuscarProducto = new javax.swing.JMenuItem();
        opcionModificarProducto = new javax.swing.JMenuItem();
        opcionEliminarProducto = new javax.swing.JMenuItem();
        listarProductos = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        opcionNuevoCarrito = new javax.swing.JMenuItem();
        OopcionBuscarCarrito = new javax.swing.JMenuItem();
        opcionModificarInformacionCarrito = new javax.swing.JMenuItem();
        opcionEliminarCarrito = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("---- SISTEMA DE COMPRAS ----");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 50);

        jPanel2.setBackground(new java.awt.Color(159, 162, 186));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        jTextField2.setEditable(false);
        jTextField2.setText("123");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("CODIGO DE PERMISO PARA MODIFICAR, Y ELIMINAR PRODUCTOS :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel2);
        jPanel2.setBounds(0, 50, 880, 370);

        opcionCrearProducto.setMnemonic('f');
        opcionCrearProducto.setText("Producto");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Crear Producto");
        openMenuItem.addActionListener(this::openMenuItemActionPerformed);
        opcionCrearProducto.add(openMenuItem);

        opcionBuscarProducto.setMnemonic('s');
        opcionBuscarProducto.setText("Buscar Producto");
        opcionBuscarProducto.addActionListener(this::opcionBuscarProductoActionPerformed);
        opcionCrearProducto.add(opcionBuscarProducto);

        opcionModificarProducto.setMnemonic('a');
        opcionModificarProducto.setText("Modificar Producto");
        opcionModificarProducto.addActionListener(this::opcionModificarProductoActionPerformed);
        opcionCrearProducto.add(opcionModificarProducto);

        opcionEliminarProducto.setMnemonic('x');
        opcionEliminarProducto.setText("Eliminar Producto");
        opcionEliminarProducto.addActionListener(this::opcionEliminarProductoActionPerformed);
        opcionCrearProducto.add(opcionEliminarProducto);

        listarProductos.setText("Listar Productos");
        listarProductos.addActionListener(this::listarProductosActionPerformed);
        opcionCrearProducto.add(listarProductos);

        menuBar.add(opcionCrearProducto);

        editMenu.setMnemonic('e');
        editMenu.setText("Carrito");

        opcionNuevoCarrito.setMnemonic('t');
        opcionNuevoCarrito.setText("Nuevo Carrito");
        opcionNuevoCarrito.addActionListener(this::opcionNuevoCarritoActionPerformed);
        editMenu.add(opcionNuevoCarrito);

        OopcionBuscarCarrito.setMnemonic('y');
        OopcionBuscarCarrito.setText("Buscar Carrito");
        OopcionBuscarCarrito.addActionListener(this::OopcionBuscarCarritoActionPerformed);
        editMenu.add(OopcionBuscarCarrito);

        opcionModificarInformacionCarrito.setMnemonic('p');
        opcionModificarInformacionCarrito.setText("Modificar Informacion");
        opcionModificarInformacionCarrito.addActionListener(this::opcionModificarInformacionCarritoActionPerformed);
        editMenu.add(opcionModificarInformacionCarrito);

        opcionEliminarCarrito.setMnemonic('d');
        opcionEliminarCarrito.setText("Eliminar Carrito");
        opcionEliminarCarrito.addActionListener(this::opcionEliminarCarritoActionPerformed);
        editMenu.add(opcionEliminarCarrito);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Acerda de nosotros");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Contacto");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEliminarProductoActionPerformed
        VEliminarProductoView eliminarProducto = new VEliminarProductoView(controlador);
        eliminarProducto.setVentanaPrincipal(this);
        eliminarProducto.setVisible(true);
        eliminarProducto.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_opcionEliminarProductoActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        VAgregarProductoView agregarProducto = new VAgregarProductoView(controlador);
        agregarProducto.setVentanaPrincipal(this);
        agregarProducto.setVisible(true);
        agregarProducto.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void opcionBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBuscarProductoActionPerformed
        VBuscarProductoView buscarProducto = new VBuscarProductoView(controlador);
        buscarProducto.setVentanaPrincipal(this);
        buscarProducto.setVisible(true);
        buscarProducto.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_opcionBuscarProductoActionPerformed

    private void opcionModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionModificarProductoActionPerformed
        VModificarProductoView agregarProducto = new VModificarProductoView(controlador);
        agregarProducto.setVentanaPrincipal(this);
        agregarProducto.setVisible(true);
        agregarProducto.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_opcionModificarProductoActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void listarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProductosActionPerformed
        
        VListarProductosView listarProductos = new VListarProductosView();
        listarProductos.setVentanaPrincipal(this);
        listarProductos.setVisible(true);
        listarProductos.setLocationRelativeTo(null);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_listarProductosActionPerformed

    private void opcionNuevoCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionNuevoCarritoActionPerformed
        VNuevoCarritoView nuevoCarrito = new VNuevoCarritoView();
        nuevoCarrito.setVentanaPrincipal(this);
        nuevoCarrito.setVisible(true);
        nuevoCarrito.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_opcionNuevoCarritoActionPerformed

    private void OopcionBuscarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OopcionBuscarCarritoActionPerformed
        VBuscarCarritoView buscarCarrito = new VBuscarCarritoView();
        buscarCarrito.setVentanaPrincipal(this);
        buscarCarrito.setVisible(true);
        buscarCarrito.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_OopcionBuscarCarritoActionPerformed

    private void opcionModificarInformacionCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionModificarInformacionCarritoActionPerformed
        VModificarCarritoView modificarCarrito = new VModificarCarritoView();
        modificarCarrito.setVentanaPrincipal(this);
        modificarCarrito.setVisible(true);
        modificarCarrito.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_opcionModificarInformacionCarritoActionPerformed

    private void opcionEliminarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEliminarCarritoActionPerformed
        VEliminarCarritoView eliminarCarrito = new VEliminarCarritoView();
        eliminarCarrito.setVentanaPrincipal(this);
        eliminarCarrito.setVisible(true);
        eliminarCarrito.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_opcionEliminarCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OopcionBuscarCarrito;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuItem listarProductos;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem opcionBuscarProducto;
    private javax.swing.JMenu opcionCrearProducto;
    private javax.swing.JMenuItem opcionEliminarCarrito;
    private javax.swing.JMenuItem opcionEliminarProducto;
    private javax.swing.JMenuItem opcionModificarInformacionCarrito;
    private javax.swing.JMenuItem opcionModificarProducto;
    private javax.swing.JMenuItem opcionNuevoCarrito;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables

}
